@startuml 

skinparam linetype ortho
skinparam shadowing false
skinparam handwritten false
skinparam nodesep 100
skinparam ranksep 60

entity "account" as account {
  *id: uint64 <<PK>>
  --
  username : varchar(64) <<UQ>>
  password : varchar(60)
  email : varchar(64) <<nullable, UQ>>
  avatar_url: varchar(255) <<nullable>>
  active: bool default(false)
  created_at: datetime
  updated_at: datetime
  role: uint8
}

entity "shop" as shop {
  *id: uint64 <<PK>>
  *account_id: uint64 <<FK, UQ>>
  --
  name: varchar(64) <<UQ>>
  summary: varchar(255)
  description: text
  active: bool default(false)
  created_at: datetime
  updated_at: datetime
}

entity "product" as product {
  *id: uint64 <<PK>>
  *shop_id: uint64 <<FK>>
  --
  name: varchar(128)
  summary: varchar(255)
  description: text
  price: uint64
  stock: uint32
  is_latest: bool
  created_at: datetime
  updated_at: datetime
}

entity "cart" as cart {
  *id: uint64 <<PK>>
  *account_id: uint64 <<FK, UQ>>
  --
  created_at: datetime
  updated_at: datetime
}

entity "cart_item" as cart_item {
  *id: uint64 <<PK>>
  *cart_id: uint64 <<FK>>
  *product_id: uint64 <<FK>>
  --
  quantity: uint32
}

entity "wishlist" as wishlist {
  *id: uint64<<PK>>
  *account_id: uint64<<FK>>
  *product_id: uint64<<FK>>
  --

  --
  CONSTRAINT
  UNIQUE(account_id, product_id)
}


product ||--o{wishlist

' --- RELASI ---
' Satu Akun punya satu Toko (jika rolenya seller)
account ||--|| shop

' Satu Akun punya satu Keranjang
account ||--|| cart

' Satu Toko punya banyak Produk
shop ||--o{ product

' Satu Keranjang punya banyak Item
cart ||--o{ cart_item

' Satu Produk bisa ada di banyak Item Keranjang
product ||--o{ cart_item
@enduml