# =======================================================
# Konfigurasi Air untuk: product-service
# =======================================================

root = "."
tmp_dir = "tmp"

[build]
  # 1. PERINTAH BUILD YANG BENAR
  #    Secara eksplisit menunjuk ke direktori service Anda.
  cmd = "go build -o ./tmp/account.exe ./cmd/account-service"

  # 2. NAMA BINARY YANG BENAR
  #    Harus sama dengan nama output (-o) dari perintah 'cmd'.
  bin = "./tmp/account.exe"

  # (Rekomendasi) Agar lebih efisien, watch direktori yang relevan saja.
  include_dir = ["cmd/account-service", "internal", "pkg"]
  
  include_ext = ["go", "tpl", "tmpl", "html", "env"]
  exclude_dir = ["assets", "tmp", "vendor"]
  
  # Polling sangat disarankan untuk Windows/WSL
  poll = true
  poll_interval = 500

[log]
  time = true

[misc]
  clean_on_exit = true