-- Seed data regencies
BEGIN;

INSERT INTO regencies (id, province_id, name) VALUES ('11.01', '11', 'KAB. ACEH SELATAN');
INSERT INTO regencies (id, province_id, name) VALUES ('11.02', '11', 'KAB. ACEH TENGGARA');
INSERT INTO regencies (id, province_id, name) VALUES ('11.03', '11', 'KAB. ACEH TIMUR');
INSERT INTO regencies (id, province_id, name) VALUES ('11.04', '11', 'KAB. ACEH TENGAH');
INSERT INTO regencies (id, province_id, name) VALUES ('11.05', '11', 'KAB. ACEH BARAT');
INSERT INTO regencies (id, province_id, name) VALUES ('11.06', '11', 'KAB. ACEH BESAR');
INSERT INTO regencies (id, province_id, name) VALUES ('11.07', '11', 'KAB. PIDIE');
INSERT INTO regencies (id, province_id, name) VALUES ('11.08', '11', 'KAB. ACEH UTARA');
INSERT INTO regencies (id, province_id, name) VALUES ('11.09', '11', 'KAB. SIMEULUE');
INSERT INTO regencies (id, province_id, name) VALUES ('11.10', '11', 'KAB. ACEH SINGKIL');
INSERT INTO regencies (id, province_id, name) VALUES ('11.11', '11', 'KAB. BIREUEN');
INSERT INTO regencies (id, province_id, name) VALUES ('11.12', '11', 'KAB. ACEH BARAT DAYA');
INSERT INTO regencies (id, province_id, name) VALUES ('11.13', '11', 'KAB. GAYO LUES');
INSERT INTO regencies (id, province_id, name) VALUES ('11.14', '11', 'KAB. ACEH JAYA');
INSERT INTO regencies (id, province_id, name) VALUES ('11.15', '11', 'KAB. NAGAN RAYA');
INSERT INTO regencies (id, province_id, name) VALUES ('11.16', '11', 'KAB. ACEH TAMIANG');
INSERT INTO regencies (id, province_id, name) VALUES ('11.17', '11', 'KAB. BENER MERIAH');
INSERT INTO regencies (id, province_id, name) VALUES ('11.18', '11', 'KAB. PIDIE JAYA');
INSERT INTO regencies (id, province_id, name) VALUES ('11.71', '11', 'KOTA BANDA ACEH');
INSERT INTO regencies (id, province_id, name) VALUES ('11.72', '11', 'KOTA SABANG');
INSERT INTO regencies (id, province_id, name) VALUES ('11.73', '11', 'KOTA LHOKSEUMAWE');
INSERT INTO regencies (id, province_id, name) VALUES ('11.74', '11', 'KOTA LANGSA');
INSERT INTO regencies (id, province_id, name) VALUES ('11.75', '11', 'KOTA SUBULUSSALAM');
INSERT INTO regencies (id, province_id, name) VALUES ('12.01', '12', 'KAB. TAPANULI TENGAH');
INSERT INTO regencies (id, province_id, name) VALUES ('12.02', '12', 'KAB. TAPANULI UTARA');
INSERT INTO regencies (id, province_id, name) VALUES ('12.03', '12', 'KAB. TAPANULI SELATAN');
INSERT INTO regencies (id, province_id, name) VALUES ('12.04', '12', 'KAB. NIAS');
INSERT INTO regencies (id, province_id, name) VALUES ('12.05', '12', 'KAB. LANGKAT');
INSERT INTO regencies (id, province_id, name) VALUES ('12.06', '12', 'KAB. KARO');
INSERT INTO regencies (id, province_id, name) VALUES ('12.07', '12', 'KAB. DELI SERDANG');
INSERT INTO regencies (id, province_id, name) VALUES ('12.08', '12', 'KAB. SIMALUNGUN');
INSERT INTO regencies (id, province_id, name) VALUES ('12.09', '12', 'KAB. ASAHAN');
INSERT INTO regencies (id, province_id, name) VALUES ('12.10', '12', 'KAB. LABUHANBATU');
INSERT INTO regencies (id, province_id, name) VALUES ('12.11', '12', 'KAB. DAIRI');
INSERT INTO regencies (id, province_id, name) VALUES ('12.12', '12', 'KAB. TOBA SAMOSIR');
INSERT INTO regencies (id, province_id, name) VALUES ('12.13', '12', 'KAB. MANDAILING NATAL');
INSERT INTO regencies (id, province_id, name) VALUES ('12.14', '12', 'KAB. NIAS SELATAN');
INSERT INTO regencies (id, province_id, name) VALUES ('12.15', '12', 'KAB. PAKPAK BHARAT');
INSERT INTO regencies (id, province_id, name) VALUES ('12.16', '12', 'KAB. HUMBANG HASUNDUTAN');
INSERT INTO regencies (id, province_id, name) VALUES ('12.17', '12', 'KAB. SAMOSIR');
INSERT INTO regencies (id, province_id, name) VALUES ('12.18', '12', 'KAB. SERDANG BEDAGAI');
INSERT INTO regencies (id, province_id, name) VALUES ('12.19', '12', 'KAB. BATU BARA');
INSERT INTO regencies (id, province_id, name) VALUES ('12.20', '12', 'KAB. PADANG LAWAS UTARA');
INSERT INTO regencies (id, province_id, name) VALUES ('12.21', '12', 'KAB. PADANG LAWAS');
INSERT INTO regencies (id, province_id, name) VALUES ('12.22', '12', 'KAB. LABUHANBATU SELATAN');
INSERT INTO regencies (id, province_id, name) VALUES ('12.23', '12', 'KAB. LABUHANBATU UTARA');
INSERT INTO regencies (id, province_id, name) VALUES ('12.24', '12', 'KAB. NIAS UTARA');
INSERT INTO regencies (id, province_id, name) VALUES ('12.25', '12', 'KAB. NIAS BARAT');
INSERT INTO regencies (id, province_id, name) VALUES ('12.71', '12', 'KOTA MEDAN');
INSERT INTO regencies (id, province_id, name) VALUES ('12.72', '12', 'KOTA PEMATANGSIANTAR');
INSERT INTO regencies (id, province_id, name) VALUES ('12.73', '12', 'KOTA SIBOLGA');
INSERT INTO regencies (id, province_id, name) VALUES ('12.74', '12', 'KOTA TANJUNG BALAI');
INSERT INTO regencies (id, province_id, name) VALUES ('12.75', '12', 'KOTA BINJAI');
INSERT INTO regencies (id, province_id, name) VALUES ('12.76', '12', 'KOTA TEBING TINGGI');
INSERT INTO regencies (id, province_id, name) VALUES ('12.77', '12', 'KOTA PADANG SIDEMPUAN');
INSERT INTO regencies (id, province_id, name) VALUES ('12.78', '12', 'KOTA GUNUNGSITOLI');
INSERT INTO regencies (id, province_id, name) VALUES ('13.01', '13', 'KAB. PESISIR SELATAN');
INSERT INTO regencies (id, province_id, name) VALUES ('13.02', '13', 'KAB. SOLOK');
INSERT INTO regencies (id, province_id, name) VALUES ('13.03', '13', 'KAB. SIJUNJUNG');
INSERT INTO regencies (id, province_id, name) VALUES ('13.04', '13', 'KAB. TANAH DATAR');
INSERT INTO regencies (id, province_id, name) VALUES ('13.05', '13', 'KAB. PADANG PARIAMAN');
INSERT INTO regencies (id, province_id, name) VALUES ('13.06', '13', 'KAB. AGAM');
INSERT INTO regencies (id, province_id, name) VALUES ('13.07', '13', 'KAB. LIMA PULUH KOTA');
INSERT INTO regencies (id, province_id, name) VALUES ('13.08', '13', 'KAB. PASAMAN');
INSERT INTO regencies (id, province_id, name) VALUES ('13.09', '13', 'KAB. KEPULAUAN MENTAWAI');
INSERT INTO regencies (id, province_id, name) VALUES ('13.10', '13', 'KAB. DHARMASRAYA');
INSERT INTO regencies (id, province_id, name) VALUES ('13.11', '13', 'KAB. SOLOK SELATAN');
INSERT INTO regencies (id, province_id, name) VALUES ('13.12', '13', 'KAB. PASAMAN BARAT');
INSERT INTO regencies (id, province_id, name) VALUES ('13.71', '13', 'KOTA PADANG');
INSERT INTO regencies (id, province_id, name) VALUES ('13.72', '13', 'KOTA SOLOK');
INSERT INTO regencies (id, province_id, name) VALUES ('13.73', '13', 'KOTA SAWAHLUNTO');
INSERT INTO regencies (id, province_id, name) VALUES ('13.74', '13', 'KOTA PADANG PANJANG');
INSERT INTO regencies (id, province_id, name) VALUES ('13.75', '13', 'KOTA BUKITTINGGI');
INSERT INTO regencies (id, province_id, name) VALUES ('13.76', '13', 'KOTA PAYAKUMBUH');
INSERT INTO regencies (id, province_id, name) VALUES ('13.77', '13', 'KOTA PARIAMAN');
INSERT INTO regencies (id, province_id, name) VALUES ('14.01', '14', 'KAB. KAMPAR');
INSERT INTO regencies (id, province_id, name) VALUES ('14.02', '14', 'KAB. INDRAGIRI HULU');
INSERT INTO regencies (id, province_id, name) VALUES ('14.03', '14', 'KAB. BENGKALIS');
INSERT INTO regencies (id, province_id, name) VALUES ('14.04', '14', 'KAB. INDRAGIRI HILIR');
INSERT INTO regencies (id, province_id, name) VALUES ('14.05', '14', 'KAB. PELALAWAN');
INSERT INTO regencies (id, province_id, name) VALUES ('14.06', '14', 'KAB. ROKAN HULU');
INSERT INTO regencies (id, province_id, name) VALUES ('14.07', '14', 'KAB. ROKAN HILIR');
INSERT INTO regencies (id, province_id, name) VALUES ('14.08', '14', 'KAB. SIAK');
INSERT INTO regencies (id, province_id, name) VALUES ('14.09', '14', 'KAB. KUANTAN SINGINGI');
INSERT INTO regencies (id, province_id, name) VALUES ('14.10', '14', 'KAB. KEPULAUAN MERANTI');
INSERT INTO regencies (id, province_id, name) VALUES ('14.71', '14', 'KOTA PEKANBARU');
INSERT INTO regencies (id, province_id, name) VALUES ('14.72', '14', 'KOTA DUMAI');
INSERT INTO regencies (id, province_id, name) VALUES ('15.01', '15', 'KAB. KERINCI');
INSERT INTO regencies (id, province_id, name) VALUES ('15.02', '15', 'KAB. MERANGIN');
INSERT INTO regencies (id, province_id, name) VALUES ('15.03', '15', 'KAB. SAROLANGUN');
INSERT INTO regencies (id, province_id, name) VALUES ('15.04', '15', 'KAB. BATANGHARI');
INSERT INTO regencies (id, province_id, name) VALUES ('15.05', '15', 'KAB. MUARO JAMBI');
INSERT INTO regencies (id, province_id, name) VALUES ('15.06', '15', 'KAB. TANJUNG JABUNG BARAT');
INSERT INTO regencies (id, province_id, name) VALUES ('15.07', '15', 'KAB. TANJUNG JABUNG TIMUR');
INSERT INTO regencies (id, province_id, name) VALUES ('15.08', '15', 'KAB. BUNGO');
INSERT INTO regencies (id, province_id, name) VALUES ('15.09', '15', 'KAB. TEBO');
INSERT INTO regencies (id, province_id, name) VALUES ('15.71', '15', 'KOTA JAMBI');
INSERT INTO regencies (id, province_id, name) VALUES ('15.72', '15', 'KOTA SUNGAI PENUH');
INSERT INTO regencies (id, province_id, name) VALUES ('16.01', '16', 'KAB. OGAN KOMERING ULU');
INSERT INTO regencies (id, province_id, name) VALUES ('16.02', '16', 'KAB. OGAN KOMERING ILIR');
INSERT INTO regencies (id, province_id, name) VALUES ('16.03', '16', 'KAB. MUARA ENIM');
INSERT INTO regencies (id, province_id, name) VALUES ('16.04', '16', 'KAB. LAHAT');
INSERT INTO regencies (id, province_id, name) VALUES ('16.05', '16', 'KAB. MUSI RAWAS');
INSERT INTO regencies (id, province_id, name) VALUES ('16.06', '16', 'KAB. MUSI BANYUASIN');
INSERT INTO regencies (id, province_id, name) VALUES ('16.07', '16', 'KAB. BANYUASIN');
INSERT INTO regencies (id, province_id, name) VALUES ('16.08', '16', 'KAB. OGAN KOMERING ULUTIMUR');
INSERT INTO regencies (id, province_id, name) VALUES ('16.09', '16', 'KAB. OGAN KOMERING ULUSELATAN');
INSERT INTO regencies (id, province_id, name) VALUES ('16.10', '16', 'KAB. OGAN ILIR');
INSERT INTO regencies (id, province_id, name) VALUES ('16.11', '16', 'KAB. EMPAT LAWANG');
INSERT INTO regencies (id, province_id, name) VALUES ('16.12', '16', 'KAB. PENUKAL ABAB LEMATANGILIR');
INSERT INTO regencies (id, province_id, name) VALUES ('16.13', '16', 'KAB. MUSI RAWAS UTARA');
INSERT INTO regencies (id, province_id, name) VALUES ('16.71', '16', 'KOTA PALEMBANG');
INSERT INTO regencies (id, province_id, name) VALUES ('16.72', '16', 'KOTA PAGAR ALAM');
INSERT INTO regencies (id, province_id, name) VALUES ('16.73', '16', 'KOTA LUBUK LINGGAU');
INSERT INTO regencies (id, province_id, name) VALUES ('16.74', '16', 'KOTA PRABUMULIH');
INSERT INTO regencies (id, province_id, name) VALUES ('17.01', '17', 'KAB. BENGKULU SELATAN');
INSERT INTO regencies (id, province_id, name) VALUES ('17.02', '17', 'KAB. REJANG LEBONG');
INSERT INTO regencies (id, province_id, name) VALUES ('17.03', '17', 'KAB. BENGKULU UTARA');
INSERT INTO regencies (id, province_id, name) VALUES ('17.04', '17', 'KAB. KAUR');
INSERT INTO regencies (id, province_id, name) VALUES ('17.05', '17', 'KAB. SELUMA');
INSERT INTO regencies (id, province_id, name) VALUES ('17.06', '17', 'KAB. MUKO MUKO');
INSERT INTO regencies (id, province_id, name) VALUES ('17.07', '17', 'KAB. LEBONG');
INSERT INTO regencies (id, province_id, name) VALUES ('17.08', '17', 'KAB. KEPAHIANG');
INSERT INTO regencies (id, province_id, name) VALUES ('17.09', '17', 'KAB. BENGKULU TENGAH');
INSERT INTO regencies (id, province_id, name) VALUES ('17.71', '17', 'KOTA BENGKULU');
INSERT INTO regencies (id, province_id, name) VALUES ('18.01', '18', 'KAB. LAMPUNG SELATAN');
INSERT INTO regencies (id, province_id, name) VALUES ('18.02', '18', 'KAB. LAMPUNG TENGAH');
INSERT INTO regencies (id, province_id, name) VALUES ('18.03', '18', 'KAB. LAMPUNG UTARA');
INSERT INTO regencies (id, province_id, name) VALUES ('18.04', '18', 'KAB. LAMPUNG BARAT');
INSERT INTO regencies (id, province_id, name) VALUES ('18.05', '18', 'KAB. TULANG BAWANG');
INSERT INTO regencies (id, province_id, name) VALUES ('18.06', '18', 'KAB. TANGGAMUS');
INSERT INTO regencies (id, province_id, name) VALUES ('18.07', '18', 'KAB. LAMPUNG TIMUR');
INSERT INTO regencies (id, province_id, name) VALUES ('18.08', '18', 'KAB. WAY KANAN');
INSERT INTO regencies (id, province_id, name) VALUES ('18.09', '18', 'KAB. PESAWARAN');
INSERT INTO regencies (id, province_id, name) VALUES ('18.10', '18', 'KAB. PRINGSEWU');
INSERT INTO regencies (id, province_id, name) VALUES ('18.11', '18', 'KAB. MESUJI');
INSERT INTO regencies (id, province_id, name) VALUES ('18.12', '18', 'KAB. TULANG BAWANG BARAT');
INSERT INTO regencies (id, province_id, name) VALUES ('18.13', '18', 'KAB. PESISIR BARAT');
INSERT INTO regencies (id, province_id, name) VALUES ('18.71', '18', 'KOTA BANDAR LAMPUNG');
INSERT INTO regencies (id, province_id, name) VALUES ('18.72', '18', 'KOTA METRO');
INSERT INTO regencies (id, province_id, name) VALUES ('19.01', '19', 'KAB. BANGKA');
INSERT INTO regencies (id, province_id, name) VALUES ('19.02', '19', 'KAB. BELITUNG');
INSERT INTO regencies (id, province_id, name) VALUES ('19.03', '19', 'KAB. BANGKA SELATAN');
INSERT INTO regencies (id, province_id, name) VALUES ('19.04', '19', 'KAB. BANGKA TENGAH');
INSERT INTO regencies (id, province_id, name) VALUES ('19.05', '19', 'KAB. BANGKA BARAT');
INSERT INTO regencies (id, province_id, name) VALUES ('19.06', '19', 'KAB. BELITUNG TIMUR');
INSERT INTO regencies (id, province_id, name) VALUES ('19.71', '19', 'KOTA PANGKAL PINANG');
INSERT INTO regencies (id, province_id, name) VALUES ('21.01', '21', 'KAB. BINTAN');
INSERT INTO regencies (id, province_id, name) VALUES ('21.02', '21', 'KAB. KARIMUN');
INSERT INTO regencies (id, province_id, name) VALUES ('21.03', '21', 'KAB. NATUNA');
INSERT INTO regencies (id, province_id, name) VALUES ('21.04', '21', 'KAB. LINGGA');
INSERT INTO regencies (id, province_id, name) VALUES ('21.05', '21', 'KAB. KEPULAUAN ANAMBAS');
INSERT INTO regencies (id, province_id, name) VALUES ('21.71', '21', 'KOTA BATAM');
INSERT INTO regencies (id, province_id, name) VALUES ('21.72', '21', 'KOTA TANJUNG PINANG');
INSERT INTO regencies (id, province_id, name) VALUES ('31.01', '31', 'KAB. ADM. KEP. SERIBU');
INSERT INTO regencies (id, province_id, name) VALUES ('31.71', '31', 'KOTA ADM. JAKARTA PUSAT');
INSERT INTO regencies (id, province_id, name) VALUES ('31.72', '31', 'KOTA ADM. JAKARTA UTARA');
INSERT INTO regencies (id, province_id, name) VALUES ('31.73', '31', 'KOTA ADM. JAKARTA BARAT');
INSERT INTO regencies (id, province_id, name) VALUES ('31.74', '31', 'KOTA ADM. JAKARTA SELATAN');
INSERT INTO regencies (id, province_id, name) VALUES ('31.75', '31', 'KOTA ADM. JAKARTA TIMUR');
INSERT INTO regencies (id, province_id, name) VALUES ('32.01', '32', 'KAB. BOGOR');
INSERT INTO regencies (id, province_id, name) VALUES ('32.02', '32', 'KAB. SUKABUMI');
INSERT INTO regencies (id, province_id, name) VALUES ('32.03', '32', 'KAB. CIANJUR');
INSERT INTO regencies (id, province_id, name) VALUES ('32.04', '32', 'KAB. BANDUNG');
INSERT INTO regencies (id, province_id, name) VALUES ('32.05', '32', 'KAB. GARUT');
INSERT INTO regencies (id, province_id, name) VALUES ('32.06', '32', 'KAB. TASIKMALAYA');
INSERT INTO regencies (id, province_id, name) VALUES ('32.07', '32', 'KAB. CIAMIS');
INSERT INTO regencies (id, province_id, name) VALUES ('32.08', '32', 'KAB. KUNINGAN');
INSERT INTO regencies (id, province_id, name) VALUES ('32.09', '32', 'KAB. CIREBON');
INSERT INTO regencies (id, province_id, name) VALUES ('32.10', '32', 'KAB. MAJALENGKA');
INSERT INTO regencies (id, province_id, name) VALUES ('32.11', '32', 'KAB. SUMEDANG');
INSERT INTO regencies (id, province_id, name) VALUES ('32.12', '32', 'KAB. INDRAMAYU');
INSERT INTO regencies (id, province_id, name) VALUES ('32.13', '32', 'KAB. SUBANG');
INSERT INTO regencies (id, province_id, name) VALUES ('32.14', '32', 'KAB. PURWAKARTA');
INSERT INTO regencies (id, province_id, name) VALUES ('32.15', '32', 'KAB. KARAWANG');
INSERT INTO regencies (id, province_id, name) VALUES ('32.16', '32', 'KAB. BEKASI');
INSERT INTO regencies (id, province_id, name) VALUES ('32.17', '32', 'KAB. BANDUNG BARAT');
INSERT INTO regencies (id, province_id, name) VALUES ('32.18', '32', 'KAB. PANGANDARAN');
INSERT INTO regencies (id, province_id, name) VALUES ('32.71', '32', 'KOTA BOGOR');
INSERT INTO regencies (id, province_id, name) VALUES ('32.72', '32', 'KOTA SUKABUMI');
INSERT INTO regencies (id, province_id, name) VALUES ('32.73', '32', 'KOTA BANDUNG');
INSERT INTO regencies (id, province_id, name) VALUES ('32.74', '32', 'KOTA CIREBON');
INSERT INTO regencies (id, province_id, name) VALUES ('32.75', '32', 'KOTA BEKASI');
INSERT INTO regencies (id, province_id, name) VALUES ('32.76', '32', 'KOTA DEPOK');
INSERT INTO regencies (id, province_id, name) VALUES ('32.77', '32', 'KOTA CIMAHI');
INSERT INTO regencies (id, province_id, name) VALUES ('32.78', '32', 'KOTA TASIKMALAYA');
INSERT INTO regencies (id, province_id, name) VALUES ('32.79', '32', 'KOTA BANJAR');
INSERT INTO regencies (id, province_id, name) VALUES ('33.01', '33', 'KAB. CILACAP');
INSERT INTO regencies (id, province_id, name) VALUES ('33.02', '33', 'KAB. BANYUMAS');
INSERT INTO regencies (id, province_id, name) VALUES ('33.03', '33', 'KAB. PURBALINGGA');
INSERT INTO regencies (id, province_id, name) VALUES ('33.04', '33', 'KAB. BANJARNEGARA');
INSERT INTO regencies (id, province_id, name) VALUES ('33.05', '33', 'KAB. KEBUMEN');
INSERT INTO regencies (id, province_id, name) VALUES ('33.06', '33', 'KAB. PURWOREJO');
INSERT INTO regencies (id, province_id, name) VALUES ('33.07', '33', 'KAB. WONOSOBO');
INSERT INTO regencies (id, province_id, name) VALUES ('33.08', '33', 'KAB. MAGELANG');
INSERT INTO regencies (id, province_id, name) VALUES ('33.09', '33', 'KAB. BOYOLALI');
INSERT INTO regencies (id, province_id, name) VALUES ('33.10', '33', 'KAB. KLATEN');
INSERT INTO regencies (id, province_id, name) VALUES ('33.11', '33', 'KAB. SUKOHARJO');
INSERT INTO regencies (id, province_id, name) VALUES ('33.12', '33', 'KAB. WONOGIRI');
INSERT INTO regencies (id, province_id, name) VALUES ('33.13', '33', 'KAB. KARANGANYAR');
INSERT INTO regencies (id, province_id, name) VALUES ('33.14', '33', 'KAB. SRAGEN');
INSERT INTO regencies (id, province_id, name) VALUES ('33.15', '33', 'KAB. GROBOGAN');
INSERT INTO regencies (id, province_id, name) VALUES ('33.16', '33', 'KAB. BLORA');
INSERT INTO regencies (id, province_id, name) VALUES ('33.17', '33', 'KAB. REMBANG');
INSERT INTO regencies (id, province_id, name) VALUES ('33.18', '33', 'KAB. PATI');
INSERT INTO regencies (id, province_id, name) VALUES ('33.19', '33', 'KAB. KUDUS');
INSERT INTO regencies (id, province_id, name) VALUES ('33.20', '33', 'KAB. JEPARA');
INSERT INTO regencies (id, province_id, name) VALUES ('33.21', '33', 'KAB. DEMAK');
INSERT INTO regencies (id, province_id, name) VALUES ('33.22', '33', 'KAB. SEMARANG');
INSERT INTO regencies (id, province_id, name) VALUES ('33.23', '33', 'KAB. TEMANGGUNG');
INSERT INTO regencies (id, province_id, name) VALUES ('33.24', '33', 'KAB. KENDAL');
INSERT INTO regencies (id, province_id, name) VALUES ('33.25', '33', 'KAB. BATANG');
INSERT INTO regencies (id, province_id, name) VALUES ('33.26', '33', 'KAB. PEKALONGAN');
INSERT INTO regencies (id, province_id, name) VALUES ('33.27', '33', 'KAB. PEMALANG');
INSERT INTO regencies (id, province_id, name) VALUES ('33.28', '33', 'KAB. TEGAL');
INSERT INTO regencies (id, province_id, name) VALUES ('33.29', '33', 'KAB. BREBES');
INSERT INTO regencies (id, province_id, name) VALUES ('33.71', '33', 'KOTA MAGELANG');
INSERT INTO regencies (id, province_id, name) VALUES ('33.72', '33', 'KOTA SURAKARTA');
INSERT INTO regencies (id, province_id, name) VALUES ('33.73', '33', 'KOTA SALATIGA');
INSERT INTO regencies (id, province_id, name) VALUES ('33.74', '33', 'KOTA SEMARANG');
INSERT INTO regencies (id, province_id, name) VALUES ('33.75', '33', 'KOTA PEKALONGAN');
INSERT INTO regencies (id, province_id, name) VALUES ('33.76', '33', 'KOTA TEGAL');
INSERT INTO regencies (id, province_id, name) VALUES ('34.01', '34', 'KAB. KULON PROGO');
INSERT INTO regencies (id, province_id, name) VALUES ('34.02', '34', 'KAB. BANTUL');
INSERT INTO regencies (id, province_id, name) VALUES ('34.03', '34', 'KAB. GUNUNGKIDUL');
INSERT INTO regencies (id, province_id, name) VALUES ('34.04', '34', 'KAB. SLEMAN');
INSERT INTO regencies (id, province_id, name) VALUES ('34.71', '34', 'KOTA YOGYAKARTA');
INSERT INTO regencies (id, province_id, name) VALUES ('35.01', '35', 'KAB. PACITAN');
INSERT INTO regencies (id, province_id, name) VALUES ('35.02', '35', 'KAB. PONOROGO');
INSERT INTO regencies (id, province_id, name) VALUES ('35.03', '35', 'KAB. TRENGGALEK');
INSERT INTO regencies (id, province_id, name) VALUES ('35.04', '35', 'KAB. TULUNGAGUNG');
INSERT INTO regencies (id, province_id, name) VALUES ('35.05', '35', 'KAB. BLITAR');
INSERT INTO regencies (id, province_id, name) VALUES ('35.06', '35', 'KAB. KEDIRI');
INSERT INTO regencies (id, province_id, name) VALUES ('35.07', '35', 'KAB. MALANG');
INSERT INTO regencies (id, province_id, name) VALUES ('35.08', '35', 'KAB. LUMAJANG');
INSERT INTO regencies (id, province_id, name) VALUES ('35.09', '35', 'KAB. JEMBER');
INSERT INTO regencies (id, province_id, name) VALUES ('35.10', '35', 'KAB. BANYUWANGI');
INSERT INTO regencies (id, province_id, name) VALUES ('35.11', '35', 'KAB. BONDOWOSO');
INSERT INTO regencies (id, province_id, name) VALUES ('35.12', '35', 'KAB. SITUBONDO');
INSERT INTO regencies (id, province_id, name) VALUES ('35.13', '35', 'KAB. PROBOLINGGO');
INSERT INTO regencies (id, province_id, name) VALUES ('35.14', '35', 'KAB. PASURUAN');
INSERT INTO regencies (id, province_id, name) VALUES ('35.15', '35', 'KAB. SIDOARJO');
INSERT INTO regencies (id, province_id, name) VALUES ('35.16', '35', 'KAB. MOJOKERTO');
INSERT INTO regencies (id, province_id, name) VALUES ('35.17', '35', 'KAB. JOMBANG');
INSERT INTO regencies (id, province_id, name) VALUES ('35.18', '35', 'KAB. NGANJUK');
INSERT INTO regencies (id, province_id, name) VALUES ('35.19', '35', 'KAB. MADIUN');
INSERT INTO regencies (id, province_id, name) VALUES ('35.20', '35', 'KAB. MAGETAN');
INSERT INTO regencies (id, province_id, name) VALUES ('35.21', '35', 'KAB. NGAWI');
INSERT INTO regencies (id, province_id, name) VALUES ('35.22', '35', 'KAB. BOJONEGORO');
INSERT INTO regencies (id, province_id, name) VALUES ('35.23', '35', 'KAB. TUBAN');
INSERT INTO regencies (id, province_id, name) VALUES ('35.24', '35', 'KAB. LAMONGAN');
INSERT INTO regencies (id, province_id, name) VALUES ('35.25', '35', 'KAB. GRESIK');
INSERT INTO regencies (id, province_id, name) VALUES ('35.26', '35', 'KAB. BANGKALAN');
INSERT INTO regencies (id, province_id, name) VALUES ('35.27', '35', 'KAB. SAMPANG');
INSERT INTO regencies (id, province_id, name) VALUES ('35.28', '35', 'KAB. PAMEKASAN');
INSERT INTO regencies (id, province_id, name) VALUES ('35.29', '35', 'KAB. SUMENEP');
INSERT INTO regencies (id, province_id, name) VALUES ('35.71', '35', 'KOTA KEDIRI');
INSERT INTO regencies (id, province_id, name) VALUES ('35.72', '35', 'KOTA BLITAR');
INSERT INTO regencies (id, province_id, name) VALUES ('35.73', '35', 'KOTA MALANG');
INSERT INTO regencies (id, province_id, name) VALUES ('35.74', '35', 'KOTA PROBOLINGGO');
INSERT INTO regencies (id, province_id, name) VALUES ('35.75', '35', 'KOTA PASURUAN');
INSERT INTO regencies (id, province_id, name) VALUES ('35.76', '35', 'KOTA MOJOKERTO');
INSERT INTO regencies (id, province_id, name) VALUES ('35.77', '35', 'KOTA MADIUN');
INSERT INTO regencies (id, province_id, name) VALUES ('35.78', '35', 'KOTA SURABAYA');
INSERT INTO regencies (id, province_id, name) VALUES ('35.79', '35', 'KOTA BATU');
INSERT INTO regencies (id, province_id, name) VALUES ('36.01', '36', 'KAB. PANDEGLANG');
INSERT INTO regencies (id, province_id, name) VALUES ('36.02', '36', 'KAB. LEBAK');
INSERT INTO regencies (id, province_id, name) VALUES ('36.03', '36', 'KAB. TANGERANG');
INSERT INTO regencies (id, province_id, name) VALUES ('36.04', '36', 'KAB. SERANG');
INSERT INTO regencies (id, province_id, name) VALUES ('36.71', '36', 'KOTA TANGERANG');
INSERT INTO regencies (id, province_id, name) VALUES ('36.72', '36', 'KOTA CILEGON');
INSERT INTO regencies (id, province_id, name) VALUES ('36.73', '36', 'KOTA SERANG');
INSERT INTO regencies (id, province_id, name) VALUES ('36.74', '36', 'KOTA TANGERANG SELATAN');
INSERT INTO regencies (id, province_id, name) VALUES ('51.01', '51', 'KAB. JEMBRANA');
INSERT INTO regencies (id, province_id, name) VALUES ('51.02', '51', 'KAB. TABANAN');
INSERT INTO regencies (id, province_id, name) VALUES ('51.03', '51', 'KAB. BADUNG');
INSERT INTO regencies (id, province_id, name) VALUES ('51.04', '51', 'KAB. GIANYAR');
INSERT INTO regencies (id, province_id, name) VALUES ('51.05', '51', 'KAB. KLUNGKUNG');
INSERT INTO regencies (id, province_id, name) VALUES ('51.06', '51', 'KAB. BANGLI');
INSERT INTO regencies (id, province_id, name) VALUES ('51.07', '51', 'KAB. KARANGASEM');
INSERT INTO regencies (id, province_id, name) VALUES ('51.08', '51', 'KAB. BULELENG');
INSERT INTO regencies (id, province_id, name) VALUES ('51.71', '51', 'KOTA DENPASAR');
INSERT INTO regencies (id, province_id, name) VALUES ('52.01', '52', 'KAB. LOMBOK BARAT');
INSERT INTO regencies (id, province_id, name) VALUES ('52.02', '52', 'KAB. LOMBOK TENGAH');
INSERT INTO regencies (id, province_id, name) VALUES ('52.03', '52', 'KAB. LOMBOK TIMUR');
INSERT INTO regencies (id, province_id, name) VALUES ('52.04', '52', 'KAB. SUMBAWA');
INSERT INTO regencies (id, province_id, name) VALUES ('52.05', '52', 'KAB. DOMPU');
INSERT INTO regencies (id, province_id, name) VALUES ('52.06', '52', 'KAB. BIMA');
INSERT INTO regencies (id, province_id, name) VALUES ('52.07', '52', 'KAB. SUMBAWA BARAT');
INSERT INTO regencies (id, province_id, name) VALUES ('52.08', '52', 'KAB. LOMBOK UTARA');
INSERT INTO regencies (id, province_id, name) VALUES ('52.71', '52', 'KOTA MATARAM');
INSERT INTO regencies (id, province_id, name) VALUES ('52.72', '52', 'KOTA BIMA');
INSERT INTO regencies (id, province_id, name) VALUES ('53.01', '53', 'KAB. KUPANG');
INSERT INTO regencies (id, province_id, name) VALUES ('53.02', '53', 'KAB TIMOR TENGAH SELATAN');
INSERT INTO regencies (id, province_id, name) VALUES ('53.03', '53', 'KAB. TIMOR TENGAH UTARA');
INSERT INTO regencies (id, province_id, name) VALUES ('53.04', '53', 'KAB. BELU');
INSERT INTO regencies (id, province_id, name) VALUES ('53.05', '53', 'KAB. ALOR');
INSERT INTO regencies (id, province_id, name) VALUES ('53.06', '53', 'KAB. FLORES TIMUR');
INSERT INTO regencies (id, province_id, name) VALUES ('53.07', '53', 'KAB. SIKKA');
INSERT INTO regencies (id, province_id, name) VALUES ('53.08', '53', 'KAB. ENDE');
INSERT INTO regencies (id, province_id, name) VALUES ('53.09', '53', 'KAB. NGADA');
INSERT INTO regencies (id, province_id, name) VALUES ('53.10', '53', 'KAB. MANGGARAI');
INSERT INTO regencies (id, province_id, name) VALUES ('53.11', '53', 'KAB. SUMBA TIMUR');
INSERT INTO regencies (id, province_id, name) VALUES ('53.12', '53', 'KAB. SUMBA BARAT');
INSERT INTO regencies (id, province_id, name) VALUES ('53.13', '53', 'KAB. LEMBATA');
INSERT INTO regencies (id, province_id, name) VALUES ('53.14', '53', 'KAB. ROTE NDAO');
INSERT INTO regencies (id, province_id, name) VALUES ('53.15', '53', 'KAB. MANGGARAI BARAT');
INSERT INTO regencies (id, province_id, name) VALUES ('53.16', '53', 'KAB. NAGEKEO');
INSERT INTO regencies (id, province_id, name) VALUES ('53.17', '53', 'KAB. SUMBA TENGAH');
INSERT INTO regencies (id, province_id, name) VALUES ('53.18', '53', 'KAB. SUMBA BARAT DAYA');
INSERT INTO regencies (id, province_id, name) VALUES ('53.19', '53', 'KAB. MANGGARAI TIMUR');
INSERT INTO regencies (id, province_id, name) VALUES ('53.20', '53', 'KAB. SABU RAIJUA');
INSERT INTO regencies (id, province_id, name) VALUES ('53.21', '53', 'KAB. MALAKA');
INSERT INTO regencies (id, province_id, name) VALUES ('53.71', '53', 'KOTA KUPANG');
INSERT INTO regencies (id, province_id, name) VALUES ('61.01', '61', 'KAB. SAMBAS');
INSERT INTO regencies (id, province_id, name) VALUES ('61.02', '61', 'KAB. MEMPAWAH');
INSERT INTO regencies (id, province_id, name) VALUES ('61.03', '61', 'KAB. SANGGAU');
INSERT INTO regencies (id, province_id, name) VALUES ('61.04', '61', 'KAB. KETAPANG');
INSERT INTO regencies (id, province_id, name) VALUES ('61.05', '61', 'KAB. SINTANG');
INSERT INTO regencies (id, province_id, name) VALUES ('61.06', '61', 'KAB. KAPUAS HULU');
INSERT INTO regencies (id, province_id, name) VALUES ('61.07', '61', 'KAB. BENGKAYANG');
INSERT INTO regencies (id, province_id, name) VALUES ('61.08', '61', 'KAB. LANDAK');
INSERT INTO regencies (id, province_id, name) VALUES ('61.09', '61', 'KAB. SEKADAU');
INSERT INTO regencies (id, province_id, name) VALUES ('61.10', '61', 'KAB. MELAWI');
INSERT INTO regencies (id, province_id, name) VALUES ('61.11', '61', 'KAB. KAYONG UTARA');
INSERT INTO regencies (id, province_id, name) VALUES ('61.12', '61', 'KAB. KUBU RAYA');
INSERT INTO regencies (id, province_id, name) VALUES ('61.71', '61', 'KOTA PONTIANAK');
INSERT INTO regencies (id, province_id, name) VALUES ('61.72', '61', 'KOTA SINGKAWANG');
INSERT INTO regencies (id, province_id, name) VALUES ('62.01', '62', 'KAB. KOTAWARINGIN BARAT');
INSERT INTO regencies (id, province_id, name) VALUES ('62.02', '62', 'KAB. KOTAWARINGIN TIMUR');
INSERT INTO regencies (id, province_id, name) VALUES ('62.03', '62', 'KAB. KAPUAS');
INSERT INTO regencies (id, province_id, name) VALUES ('62.04', '62', 'KAB. BARITO SELATAN');
INSERT INTO regencies (id, province_id, name) VALUES ('62.05', '62', 'KAB. BARITO UTARA');
INSERT INTO regencies (id, province_id, name) VALUES ('62.06', '62', 'KAB. KATINGAN');
INSERT INTO regencies (id, province_id, name) VALUES ('62.07', '62', 'KAB. SERUYAN');
INSERT INTO regencies (id, province_id, name) VALUES ('62.08', '62', 'KAB. SUKAMARA');
INSERT INTO regencies (id, province_id, name) VALUES ('62.09', '62', 'KAB. LAMANDAU');
INSERT INTO regencies (id, province_id, name) VALUES ('62.10', '62', 'KAB. GUNUNG MAS');
INSERT INTO regencies (id, province_id, name) VALUES ('62.11', '62', 'KAB. PULANG PISAU');
INSERT INTO regencies (id, province_id, name) VALUES ('62.12', '62', 'KAB. MURUNG RAYA');
INSERT INTO regencies (id, province_id, name) VALUES ('62.13', '62', 'KAB. BARITO TIMUR');
INSERT INTO regencies (id, province_id, name) VALUES ('62.71', '62', 'KOTA PALANGKARAYA');
INSERT INTO regencies (id, province_id, name) VALUES ('63.01', '63', 'KAB. TANAH LAUT');
INSERT INTO regencies (id, province_id, name) VALUES ('63.02', '63', 'KAB. KOTABARU');
INSERT INTO regencies (id, province_id, name) VALUES ('63.03', '63', 'KAB. BANJAR');
INSERT INTO regencies (id, province_id, name) VALUES ('63.04', '63', 'KAB. BARITO KUALA');
INSERT INTO regencies (id, province_id, name) VALUES ('63.05', '63', 'KAB. TAPIN');
INSERT INTO regencies (id, province_id, name) VALUES ('63.06', '63', 'KAB. HULU SUNGAI SELATAN');
INSERT INTO regencies (id, province_id, name) VALUES ('63.07', '63', 'KAB. HULU SUNGAI TENGAH');
INSERT INTO regencies (id, province_id, name) VALUES ('63.08', '63', 'KAB. HULU SUNGAI UTARA');
INSERT INTO regencies (id, province_id, name) VALUES ('63.09', '63', 'KAB. TABALONG');
INSERT INTO regencies (id, province_id, name) VALUES ('63.10', '63', 'KAB. TANAH BUMBU');
INSERT INTO regencies (id, province_id, name) VALUES ('63.11', '63', 'KAB. BALANGAN');
INSERT INTO regencies (id, province_id, name) VALUES ('63.71', '63', 'KOTA BANJARMASIN');
INSERT INTO regencies (id, province_id, name) VALUES ('63.72', '63', 'KOTA BANJARBARU');
INSERT INTO regencies (id, province_id, name) VALUES ('64.01', '64', 'KAB. PASER');
INSERT INTO regencies (id, province_id, name) VALUES ('64.02', '64', 'KAB. KUTAI KARTANEGARA');
INSERT INTO regencies (id, province_id, name) VALUES ('64.03', '64', 'KAB. BERAU');
INSERT INTO regencies (id, province_id, name) VALUES ('64.07', '64', 'KAB. KUTAI BARAT');
INSERT INTO regencies (id, province_id, name) VALUES ('64.08', '64', 'KAB. KUTAI TIMUR');
INSERT INTO regencies (id, province_id, name) VALUES ('64.09', '64', 'KAB. PENAJAM PASER UTARA');
INSERT INTO regencies (id, province_id, name) VALUES ('64.11', '64', 'KAB. MAHAKAM ULU');
INSERT INTO regencies (id, province_id, name) VALUES ('64.71', '64', 'KOTA BALIKPAPAN');
INSERT INTO regencies (id, province_id, name) VALUES ('64.72', '64', 'KOTA SAMARINDA');
INSERT INTO regencies (id, province_id, name) VALUES ('64.74', '64', 'KOTA BONTANG');
INSERT INTO regencies (id, province_id, name) VALUES ('65.01', '65', 'KAB. BULUNGAN');
INSERT INTO regencies (id, province_id, name) VALUES ('65.02', '65', 'KAB. MALINAU');
INSERT INTO regencies (id, province_id, name) VALUES ('65.03', '65', 'KAB. NUNUKAN');
INSERT INTO regencies (id, province_id, name) VALUES ('65.04', '65', 'KAB. TANA TIDUNG');
INSERT INTO regencies (id, province_id, name) VALUES ('65.71', '65', 'KOTA TARAKAN');
INSERT INTO regencies (id, province_id, name) VALUES ('71.01', '71', 'KAB. BOLAANG MONGONDOW');
INSERT INTO regencies (id, province_id, name) VALUES ('71.02', '71', 'KAB. MINAHASA');
INSERT INTO regencies (id, province_id, name) VALUES ('71.03', '71', 'KAB. KEPULAUAN SANGIHE');
INSERT INTO regencies (id, province_id, name) VALUES ('71.04', '71', 'KAB. KEPULAUAN TALAUD');
INSERT INTO regencies (id, province_id, name) VALUES ('71.05', '71', 'KAB. MINAHASA SELATAN');
INSERT INTO regencies (id, province_id, name) VALUES ('71.06', '71', 'KAB. MINAHASA UTARA');
INSERT INTO regencies (id, province_id, name) VALUES ('71.07', '71', 'KAB. MINAHASA TENGGARA');
INSERT INTO regencies (id, province_id, name) VALUES ('71.08', '71', 'KAB. BOLAANG MONGONDOWUTARA');
INSERT INTO regencies (id, province_id, name) VALUES ('71.09', '71', 'KAB. KEP. SIAU TAGULANDANGBIARO');
INSERT INTO regencies (id, province_id, name) VALUES ('71.10', '71', 'KAB. BOLAANG MONGONDOWTIMUR');
INSERT INTO regencies (id, province_id, name) VALUES ('71.11', '71', 'KAB. BOLAANG MONGONDOWSELATAN');
INSERT INTO regencies (id, province_id, name) VALUES ('71.71', '71', 'KOTA MANADO');
INSERT INTO regencies (id, province_id, name) VALUES ('71.72', '71', 'KOTA BITUNG');
INSERT INTO regencies (id, province_id, name) VALUES ('71.73', '71', 'KOTA TOMOHON');
INSERT INTO regencies (id, province_id, name) VALUES ('71.74', '71', 'KOTA KOTAMOBAGU');
INSERT INTO regencies (id, province_id, name) VALUES ('72.01', '72', 'KAB. BANGGAI');
INSERT INTO regencies (id, province_id, name) VALUES ('72.02', '72', 'KAB. POSO');
INSERT INTO regencies (id, province_id, name) VALUES ('72.03', '72', 'KAB. DONGGALA');
INSERT INTO regencies (id, province_id, name) VALUES ('72.04', '72', 'KAB. TOLI TOLI');
INSERT INTO regencies (id, province_id, name) VALUES ('72.05', '72', 'KAB. BUOL');
INSERT INTO regencies (id, province_id, name) VALUES ('72.06', '72', 'KAB. MOROWALI');
INSERT INTO regencies (id, province_id, name) VALUES ('72.07', '72', 'KAB. BANGGAI KEPULAUAN');
INSERT INTO regencies (id, province_id, name) VALUES ('72.08', '72', 'KAB. PARIGI MOUTONG');
INSERT INTO regencies (id, province_id, name) VALUES ('72.09', '72', 'KAB. TOJO UNA UNA');
INSERT INTO regencies (id, province_id, name) VALUES ('72.10', '72', 'KAB. SIGI');
INSERT INTO regencies (id, province_id, name) VALUES ('72.11', '72', 'KAB. BANGGAI LAUT');
INSERT INTO regencies (id, province_id, name) VALUES ('72.12', '72', 'KAB. MOROWALI UTARA');
INSERT INTO regencies (id, province_id, name) VALUES ('72.71', '72', 'KOTA PALU');
INSERT INTO regencies (id, province_id, name) VALUES ('73.01', '73', 'KAB. KEPULAUAN SELAYAR');
INSERT INTO regencies (id, province_id, name) VALUES ('73.02', '73', 'KAB. BULUKUMBA');
INSERT INTO regencies (id, province_id, name) VALUES ('73.03', '73', 'KAB. BANTAENG');
INSERT INTO regencies (id, province_id, name) VALUES ('73.04', '73', 'KAB. JENEPONTO');
INSERT INTO regencies (id, province_id, name) VALUES ('73.05', '73', 'KAB. TAKALAR');
INSERT INTO regencies (id, province_id, name) VALUES ('73.06', '73', 'KAB. GOWA');
INSERT INTO regencies (id, province_id, name) VALUES ('73.07', '73', 'KAB. SINJAI');
INSERT INTO regencies (id, province_id, name) VALUES ('73.08', '73', 'KAB. BONE');
INSERT INTO regencies (id, province_id, name) VALUES ('73.09', '73', 'KAB. MAROS');
INSERT INTO regencies (id, province_id, name) VALUES ('73.10', '73', 'KAB. PANGKAJENE KEPULAUAN');
INSERT INTO regencies (id, province_id, name) VALUES ('73.11', '73', 'KAB. BARRU');
INSERT INTO regencies (id, province_id, name) VALUES ('73.12', '73', 'KAB. SOPPENG');
INSERT INTO regencies (id, province_id, name) VALUES ('73.13', '73', 'KAB. WAJO');
INSERT INTO regencies (id, province_id, name) VALUES ('73.14', '73', 'KAB. SIDENRENG RAPPANG');
INSERT INTO regencies (id, province_id, name) VALUES ('73.15', '73', 'KAB. PINRANG');
INSERT INTO regencies (id, province_id, name) VALUES ('73.16', '73', 'KAB. ENREKANG');
INSERT INTO regencies (id, province_id, name) VALUES ('73.17', '73', 'KAB. LUWU');
INSERT INTO regencies (id, province_id, name) VALUES ('73.18', '73', 'KAB. TANA TORAJA');
INSERT INTO regencies (id, province_id, name) VALUES ('73.22', '73', 'KAB. LUWU UTARA');
INSERT INTO regencies (id, province_id, name) VALUES ('73.24', '73', 'KAB. LUWU TIMUR');
INSERT INTO regencies (id, province_id, name) VALUES ('73.26', '73', 'KAB. TORAJA UTARA');
INSERT INTO regencies (id, province_id, name) VALUES ('73.71', '73', 'KOTA MAKASSAR');
INSERT INTO regencies (id, province_id, name) VALUES ('73.72', '73', 'KOTA PARE PARE');
INSERT INTO regencies (id, province_id, name) VALUES ('73.73', '73', 'KOTA PALOPO');
INSERT INTO regencies (id, province_id, name) VALUES ('74.01', '74', 'KAB. KOLAKA');
INSERT INTO regencies (id, province_id, name) VALUES ('74.02', '74', 'KAB. KONAWE');
INSERT INTO regencies (id, province_id, name) VALUES ('74.03', '74', 'KAB. MUNA');
INSERT INTO regencies (id, province_id, name) VALUES ('74.04', '74', 'KAB. BUTON');
INSERT INTO regencies (id, province_id, name) VALUES ('74.05', '74', 'KAB. KONAWE SELATAN');
INSERT INTO regencies (id, province_id, name) VALUES ('74.06', '74', 'KAB. BOMBANA');
INSERT INTO regencies (id, province_id, name) VALUES ('74.07', '74', 'KAB. WAKATOBI');
INSERT INTO regencies (id, province_id, name) VALUES ('74.08', '74', 'KAB. KOLAKA UTARA');
INSERT INTO regencies (id, province_id, name) VALUES ('74.09', '74', 'KAB. KONAWE UTARA');
INSERT INTO regencies (id, province_id, name) VALUES ('74.10', '74', 'KAB. BUTON UTARA');
INSERT INTO regencies (id, province_id, name) VALUES ('74.11', '74', 'KAB. KOLAKA TIMUR');
INSERT INTO regencies (id, province_id, name) VALUES ('74.12', '74', 'KAB. KONAWE KEPULAUAN');
INSERT INTO regencies (id, province_id, name) VALUES ('74.13', '74', 'KAB. MUNA BARAT');
INSERT INTO regencies (id, province_id, name) VALUES ('74.14', '74', 'KAB. BUTON TENGAH');
INSERT INTO regencies (id, province_id, name) VALUES ('74.15', '74', 'KAB. BUTON SELATAN');
INSERT INTO regencies (id, province_id, name) VALUES ('74.71', '74', 'KOTA KENDARI');
INSERT INTO regencies (id, province_id, name) VALUES ('74.72', '74', 'KOTA BAU BAU');
INSERT INTO regencies (id, province_id, name) VALUES ('75.01', '75', 'KAB. GORONTALO');
INSERT INTO regencies (id, province_id, name) VALUES ('75.02', '75', 'KAB. BOALEMO');
INSERT INTO regencies (id, province_id, name) VALUES ('75.03', '75', 'KAB. BONE BOLANGO');
INSERT INTO regencies (id, province_id, name) VALUES ('75.04', '75', 'KAB. PAHUWATO');
INSERT INTO regencies (id, province_id, name) VALUES ('75.05', '75', 'KAB. GORONTALO UTARA');
INSERT INTO regencies (id, province_id, name) VALUES ('75.71', '75', 'KOTA GORONTALO');
INSERT INTO regencies (id, province_id, name) VALUES ('76.01', '76', 'KAB. PASANGKAYU');
INSERT INTO regencies (id, province_id, name) VALUES ('76.02', '76', 'KAB. MAMUJU');
INSERT INTO regencies (id, province_id, name) VALUES ('76.03', '76', 'KAB. MAMASA');
INSERT INTO regencies (id, province_id, name) VALUES ('76.04', '76', 'KAB. POLEWALI MANDAR');
INSERT INTO regencies (id, province_id, name) VALUES ('76.05', '76', 'KAB. MAJENE');
INSERT INTO regencies (id, province_id, name) VALUES ('76.06', '76', 'KAB. MAMUJU TENGAH');
INSERT INTO regencies (id, province_id, name) VALUES ('81.01', '81', 'KAB. MALUKU TENGAH');
INSERT INTO regencies (id, province_id, name) VALUES ('81.02', '81', 'KAB. MALUKU TENGGARA');
INSERT INTO regencies (id, province_id, name) VALUES ('81.03', '81', 'KAB. KEPULAUAN TANIMBAR');
INSERT INTO regencies (id, province_id, name) VALUES ('81.04', '81', 'KAB. BURU');
INSERT INTO regencies (id, province_id, name) VALUES ('81.05', '81', 'KAB. SERAM BAGIAN TIMUR');
INSERT INTO regencies (id, province_id, name) VALUES ('81.06', '81', 'KAB. SERAM BAGIAN BARAT');
INSERT INTO regencies (id, province_id, name) VALUES ('81.07', '81', 'KAB. KEPULAUAN ARU');
INSERT INTO regencies (id, province_id, name) VALUES ('81.08', '81', 'KAB. MALUKU BARAT DAYA');
INSERT INTO regencies (id, province_id, name) VALUES ('81.09', '81', 'KAB. BURU SELATAN');
INSERT INTO regencies (id, province_id, name) VALUES ('81.71', '81', 'KOTA AMBON');
INSERT INTO regencies (id, province_id, name) VALUES ('81.72', '81', 'KOTA TUAL');
INSERT INTO regencies (id, province_id, name) VALUES ('82.01', '82', 'KAB. HALMAHERA BARAT');
INSERT INTO regencies (id, province_id, name) VALUES ('82.02', '82', 'KAB. HALMAHERA TENGAH');
INSERT INTO regencies (id, province_id, name) VALUES ('82.03', '82', 'KAB. HALMAHERA UTARA');
INSERT INTO regencies (id, province_id, name) VALUES ('82.04', '82', 'KAB. HALMAHERA SELATAN');
INSERT INTO regencies (id, province_id, name) VALUES ('82.05', '82', 'KAB. KEPULAUAN SULA');
INSERT INTO regencies (id, province_id, name) VALUES ('82.06', '82', 'KAB. HALMAHERA TIMUR');
INSERT INTO regencies (id, province_id, name) VALUES ('82.07', '82', 'KAB. PULAU MOROTAI');
INSERT INTO regencies (id, province_id, name) VALUES ('82.08', '82', 'KAB. PULAU TALIABU');
INSERT INTO regencies (id, province_id, name) VALUES ('82.71', '82', 'KOTA TERNATE');
INSERT INTO regencies (id, province_id, name) VALUES ('82.72', '82', 'KOTA TIDORE KEPULAUAN');
INSERT INTO regencies (id, province_id, name) VALUES ('91.01', '91', 'KAB. MERAUKE');
INSERT INTO regencies (id, province_id, name) VALUES ('91.02', '91', 'KAB. JAYAWIJAYA');
INSERT INTO regencies (id, province_id, name) VALUES ('91.03', '91', 'KAB. JAYAPURA');
INSERT INTO regencies (id, province_id, name) VALUES ('91.04', '91', 'KAB. NABIRE');
INSERT INTO regencies (id, province_id, name) VALUES ('91.05', '91', 'KAB. KEPULAUAN YAPEN');
INSERT INTO regencies (id, province_id, name) VALUES ('91.06', '91', 'KAB. BIAK NUMFOR');
INSERT INTO regencies (id, province_id, name) VALUES ('91.07', '91', 'KAB. PUNCAK JAYA');
INSERT INTO regencies (id, province_id, name) VALUES ('91.08', '91', 'KAB. PANIAI');
INSERT INTO regencies (id, province_id, name) VALUES ('91.09', '91', 'KAB. MIMIKA');
INSERT INTO regencies (id, province_id, name) VALUES ('91.10', '91', 'KAB. SARMI');
INSERT INTO regencies (id, province_id, name) VALUES ('91.11', '91', 'KAB. KEEROM');
INSERT INTO regencies (id, province_id, name) VALUES ('91.12', '91', 'KAB PEGUNUNGAN BINTANG');
INSERT INTO regencies (id, province_id, name) VALUES ('91.13', '91', 'KAB. YAHUKIMO');
INSERT INTO regencies (id, province_id, name) VALUES ('91.14', '91', 'KAB. TOLIKARA');
INSERT INTO regencies (id, province_id, name) VALUES ('91.15', '91', 'KAB. WAROPEN');
INSERT INTO regencies (id, province_id, name) VALUES ('91.16', '91', 'KAB. BOVEN DIGOEL');
INSERT INTO regencies (id, province_id, name) VALUES ('91.17', '91', 'KAB. MAPPI');
INSERT INTO regencies (id, province_id, name) VALUES ('91.18', '91', 'KAB. ASMAT');
INSERT INTO regencies (id, province_id, name) VALUES ('91.19', '91', 'KAB. SUPIORI');
INSERT INTO regencies (id, province_id, name) VALUES ('91.20', '91', 'KAB. MAMBERAMO RAYA');
INSERT INTO regencies (id, province_id, name) VALUES ('91.21', '91', 'KAB. MAMBERAMO TENGAH');
INSERT INTO regencies (id, province_id, name) VALUES ('91.22', '91', 'KAB. YALIMO');
INSERT INTO regencies (id, province_id, name) VALUES ('91.23', '91', 'KAB. LANNY JAYA');
INSERT INTO regencies (id, province_id, name) VALUES ('91.24', '91', 'KAB. NDUGA');
INSERT INTO regencies (id, province_id, name) VALUES ('91.25', '91', 'KAB. PUNCAK');
INSERT INTO regencies (id, province_id, name) VALUES ('91.26', '91', 'KAB. DOGIYAI');
INSERT INTO regencies (id, province_id, name) VALUES ('91.27', '91', 'KAB. INTAN JAYA');
INSERT INTO regencies (id, province_id, name) VALUES ('91.28', '91', 'KAB. DEIYAI');
INSERT INTO regencies (id, province_id, name) VALUES ('91.71', '91', 'KOTA JAYAPURA');
INSERT INTO regencies (id, province_id, name) VALUES ('92.01', '92', 'KAB. SORONG');
INSERT INTO regencies (id, province_id, name) VALUES ('92.02', '92', 'KAB. MANOKWARI');
INSERT INTO regencies (id, province_id, name) VALUES ('92.03', '92', 'KAB. FAK FAK');
INSERT INTO regencies (id, province_id, name) VALUES ('92.04', '92', 'KAB. SORONG SELATAN');
INSERT INTO regencies (id, province_id, name) VALUES ('92.05', '92', 'KAB. RAJA AMPAT');
INSERT INTO regencies (id, province_id, name) VALUES ('92.06', '92', 'KAB. TELUK BINTUNI');
INSERT INTO regencies (id, province_id, name) VALUES ('92.07', '92', 'KAB. TELUK WONDAMA');
INSERT INTO regencies (id, province_id, name) VALUES ('92.08', '92', 'KAB. KAIMANA');
INSERT INTO regencies (id, province_id, name) VALUES ('92.09', '92', 'KAB. TAMBRAUW');
INSERT INTO regencies (id, province_id, name) VALUES ('92.10', '92', 'KAB. MAYBRAT');
INSERT INTO regencies (id, province_id, name) VALUES ('92.11', '92', 'KAB. MANOKWARI SELATAN');
INSERT INTO regencies (id, province_id, name) VALUES ('92.12', '92', 'KAB. PEGUNUNGAN ARFAK');
INSERT INTO regencies (id, province_id, name) VALUES ('92.71', '92', 'KOTA SORONG');

COMMIT;
