@startuml UC_BrowseSearchProducts

start
:User buka halaman produk;
:User masukkan kata kunci / filter kategori;
:Kirim request ke sistem;
:Sistem ambil data produk dari database;
:Menampilkan daftar produk sesuai filter/pencarian;
stop

@enduml
