@startuml UC_OrderHistory

start
:User buka menu Order History;
:Sistem ambil semua riwayat order user dari database;
:Menampilkan daftar order (status, tanggal, total harga);
:User bisa klik untuk lihat detail order;
stop

@enduml
