@startuml UC_TrackOrder

start
:User buka menu Order History;
:User pilih order yang ingin dilacak;
:Sistem ambil status order dari database;
:Sistem ambil data tracking dari Shipping Service;
:Tampilkan status order ke user;
stop

@enduml
