@startuml UC_WishlistCart

start
:User pilih produk;
if (Tambah ke wishlist?) then (Ya)
    :Simpan ke tabel wishlist;
    :Tampilkan notifikasi sukses;
else (Tambah ke cart?)
    :Pilih jumlah produk;
    :Tambahkan ke tabel cart;
    :Tampilkan notifikasi sukses;
endif
stop

@enduml
